// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enum.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Enum_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Enum_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Enum_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

enum MoveState : int {
  MOVE_IDLE = 0,
  MOVE_RUN = 1,
  MOVE_JUMP = 2,
  MoveState_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  MoveState_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool MoveState_IsValid(int value);
constexpr MoveState MoveState_MIN = MOVE_IDLE;
constexpr MoveState MoveState_MAX = MOVE_JUMP;
constexpr int MoveState_ARRAYSIZE = MoveState_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MoveState_descriptor();
template<typename T>
inline const std::string& MoveState_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MoveState>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MoveState_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MoveState_descriptor(), enum_t_value);
}
inline bool MoveState_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, MoveState* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MoveState>(
    MoveState_descriptor(), name, value);
}
enum ActionState : int {
  ACTION_IDLE = 0,
  ACTION_ATTACK = 1,
  ACTION_DEAD = 2,
  ACTION_SKILL = 3,
  ACTION_HIT = 4,
  ActionState_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ActionState_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ActionState_IsValid(int value);
constexpr ActionState ActionState_MIN = ACTION_IDLE;
constexpr ActionState ActionState_MAX = ACTION_HIT;
constexpr int ActionState_ARRAYSIZE = ActionState_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ActionState_descriptor();
template<typename T>
inline const std::string& ActionState_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ActionState>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ActionState_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ActionState_descriptor(), enum_t_value);
}
inline bool ActionState_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ActionState* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ActionState>(
    ActionState_descriptor(), name, value);
}
enum PlayerType : int {
  PLAYER_NONE = 0,
  PLAYER_KNIGHT = 1,
  PLAYER_MAGE = 2,
  PLAYER_ARCHER = 3,
  PlayerType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  PlayerType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool PlayerType_IsValid(int value);
constexpr PlayerType PlayerType_MIN = PLAYER_NONE;
constexpr PlayerType PlayerType_MAX = PLAYER_ARCHER;
constexpr int PlayerType_ARRAYSIZE = PlayerType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PlayerType_descriptor();
template<typename T>
inline const std::string& PlayerType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PlayerType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PlayerType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PlayerType_descriptor(), enum_t_value);
}
inline bool PlayerType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, PlayerType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PlayerType>(
    PlayerType_descriptor(), name, value);
}
enum ObjectType : int {
  OBJECT_TYPE_NONE = 0,
  OBJECT_TYPE_PLAYER = 1,
  OBJECT_TYPE_MONSTER = 2,
  OBJECT_TYPE_PROJECTILE = 3,
  ObjectType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ObjectType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ObjectType_IsValid(int value);
constexpr ObjectType ObjectType_MIN = OBJECT_TYPE_NONE;
constexpr ObjectType ObjectType_MAX = OBJECT_TYPE_PROJECTILE;
constexpr int ObjectType_ARRAYSIZE = ObjectType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ObjectType_descriptor();
template<typename T>
inline const std::string& ObjectType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ObjectType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ObjectType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ObjectType_descriptor(), enum_t_value);
}
inline bool ObjectType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ObjectType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ObjectType>(
    ObjectType_descriptor(), name, value);
}
enum ItemType : int {
  ITEM_TYPE_NONE = 0,
  ITEM_TYPE_WEAPON = 1,
  ITEM_TYPE_ARMOR = 2,
  ITEM_TYPE_CONSUMABLE = 3,
  ItemType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ItemType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ItemType_IsValid(int value);
constexpr ItemType ItemType_MIN = ITEM_TYPE_NONE;
constexpr ItemType ItemType_MAX = ITEM_TYPE_CONSUMABLE;
constexpr int ItemType_ARRAYSIZE = ItemType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ItemType_descriptor();
template<typename T>
inline const std::string& ItemType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ItemType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ItemType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ItemType_descriptor(), enum_t_value);
}
inline bool ItemType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ItemType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ItemType>(
    ItemType_descriptor(), name, value);
}
enum SkillType : int {
  SKILL_NONE = 0,
  SKILL_AUTO = 1,
  SKILL_PROJECTILE = 2,
  SKILL_AREA_CIRCLE = 3,
  SKILL_AREA_CONE = 4,
  SkillType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  SkillType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool SkillType_IsValid(int value);
constexpr SkillType SkillType_MIN = SKILL_NONE;
constexpr SkillType SkillType_MAX = SKILL_AREA_CONE;
constexpr int SkillType_ARRAYSIZE = SkillType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SkillType_descriptor();
template<typename T>
inline const std::string& SkillType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, SkillType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function SkillType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    SkillType_descriptor(), enum_t_value);
}
inline bool SkillType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, SkillType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<SkillType>(
    SkillType_descriptor(), name, value);
}
enum ConnectStatus : int {
  CONNECT_OK = 0,
  CONNECT_FAIL = 1,
  CONNECT_RECONNECT = 2,
  ConnectStatus_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ConnectStatus_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ConnectStatus_IsValid(int value);
constexpr ConnectStatus ConnectStatus_MIN = CONNECT_OK;
constexpr ConnectStatus ConnectStatus_MAX = CONNECT_RECONNECT;
constexpr int ConnectStatus_ARRAYSIZE = ConnectStatus_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ConnectStatus_descriptor();
template<typename T>
inline const std::string& ConnectStatus_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ConnectStatus>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ConnectStatus_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ConnectStatus_descriptor(), enum_t_value);
}
inline bool ConnectStatus_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ConnectStatus* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ConnectStatus>(
    ConnectStatus_descriptor(), name, value);
}
enum RoomType : int {
  ROOM_PRIVATE = 0,
  ROOM_GROUP = 1,
  ROOM_GUILD = 2,
  RoomType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  RoomType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool RoomType_IsValid(int value);
constexpr RoomType RoomType_MIN = ROOM_PRIVATE;
constexpr RoomType RoomType_MAX = ROOM_GUILD;
constexpr int RoomType_ARRAYSIZE = RoomType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* RoomType_descriptor();
template<typename T>
inline const std::string& RoomType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, RoomType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function RoomType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    RoomType_descriptor(), enum_t_value);
}
inline bool RoomType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, RoomType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<RoomType>(
    RoomType_descriptor(), name, value);
}
enum PresenceStatus : int {
  OFFLINE = 0,
  ONLINE = 1,
  IN_GAME = 2,
  AWAY = 3,
  PresenceStatus_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  PresenceStatus_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool PresenceStatus_IsValid(int value);
constexpr PresenceStatus PresenceStatus_MIN = OFFLINE;
constexpr PresenceStatus PresenceStatus_MAX = AWAY;
constexpr int PresenceStatus_ARRAYSIZE = PresenceStatus_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PresenceStatus_descriptor();
template<typename T>
inline const std::string& PresenceStatus_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PresenceStatus>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PresenceStatus_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PresenceStatus_descriptor(), enum_t_value);
}
inline bool PresenceStatus_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, PresenceStatus* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PresenceStatus>(
    PresenceStatus_descriptor(), name, value);
}
enum FriendStatus : int {
  PENDING = 0,
  ACCEPTED = 1,
  BLOCKED = 2,
  FriendStatus_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  FriendStatus_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool FriendStatus_IsValid(int value);
constexpr FriendStatus FriendStatus_MIN = PENDING;
constexpr FriendStatus FriendStatus_MAX = BLOCKED;
constexpr int FriendStatus_ARRAYSIZE = FriendStatus_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* FriendStatus_descriptor();
template<typename T>
inline const std::string& FriendStatus_Name(T enum_t_value) {
  static_assert(::std::is_same<T, FriendStatus>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function FriendStatus_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    FriendStatus_descriptor(), enum_t_value);
}
inline bool FriendStatus_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, FriendStatus* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<FriendStatus>(
    FriendStatus_descriptor(), name, value);
}
enum PartyOp : int {
  PARTY_OP_NONE = 0,
  PARTY_OP_CREATE = 100,
  PARTY_OP_INVITE = 101,
  PARTY_OP_INVITE_ACCEPT = 102,
  PARTY_OP_INVITE_REJECT = 103,
  PARTY_OP_LEAVE = 110,
  PARTY_OP_KICK = 111,
  PARTY_OP_DISBAND = 112,
  PARTY_OP_STATUS_REQ = 120,
  PartyOp_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  PartyOp_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool PartyOp_IsValid(int value);
constexpr PartyOp PartyOp_MIN = PARTY_OP_NONE;
constexpr PartyOp PartyOp_MAX = PARTY_OP_STATUS_REQ;
constexpr int PartyOp_ARRAYSIZE = PartyOp_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PartyOp_descriptor();
template<typename T>
inline const std::string& PartyOp_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PartyOp>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PartyOp_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PartyOp_descriptor(), enum_t_value);
}
inline bool PartyOp_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, PartyOp* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PartyOp>(
    PartyOp_descriptor(), name, value);
}
enum PartyResultReason : int {
  PARTY_REASON_NONE = 0,
  PARTY_REASON_OK = 1000,
  PARTY_REASON_NO_TARGET = 1001,
  PARTY_REASON_ALREADY_IN_PARTY = 1002,
  PARTY_REASON_NOT_IN_PARTY = 1003,
  PARTY_REASON_NOT_LEADER = 1004,
  PARTY_REASON_NOT_MEMBER = 1005,
  PARTY_REASON_INVALID_PARTY = 1006,
  PARTY_REASON_SELF_TARGET = 1007,
  PARTY_REASON_FULL = 1008,
  PARTY_REASON_REJECTED = 1009,
  PARTY_REASON_INTERNAL_ERROR = 1099,
  PartyResultReason_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  PartyResultReason_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool PartyResultReason_IsValid(int value);
constexpr PartyResultReason PartyResultReason_MIN = PARTY_REASON_NONE;
constexpr PartyResultReason PartyResultReason_MAX = PARTY_REASON_INTERNAL_ERROR;
constexpr int PartyResultReason_ARRAYSIZE = PartyResultReason_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PartyResultReason_descriptor();
template<typename T>
inline const std::string& PartyResultReason_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PartyResultReason>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PartyResultReason_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PartyResultReason_descriptor(), enum_t_value);
}
inline bool PartyResultReason_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, PartyResultReason* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PartyResultReason>(
    PartyResultReason_descriptor(), name, value);
}
enum QuickSlotRefType : int {
  QS_NONE = 0,
  QS_ITEM = 1,
  QS_SKILL = 2,
  QuickSlotRefType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  QuickSlotRefType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool QuickSlotRefType_IsValid(int value);
constexpr QuickSlotRefType QuickSlotRefType_MIN = QS_NONE;
constexpr QuickSlotRefType QuickSlotRefType_MAX = QS_SKILL;
constexpr int QuickSlotRefType_ARRAYSIZE = QuickSlotRefType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* QuickSlotRefType_descriptor();
template<typename T>
inline const std::string& QuickSlotRefType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, QuickSlotRefType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function QuickSlotRefType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    QuickSlotRefType_descriptor(), enum_t_value);
}
inline bool QuickSlotRefType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, QuickSlotRefType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<QuickSlotRefType>(
    QuickSlotRefType_descriptor(), name, value);
}
enum TradeCancelReason : int {
  TRADE_CANCEL_NONE = 0,
  TRADE_CANCEL_BY_SELF = 1,
  TRADE_CANCEL_DECLINED = 2,
  TRADE_CANCEL_DISCONNECT = 3,
  TRADE_CANCEL_MAP_CHANGE = 4,
  TRADE_CANCEL_TIMEOUT = 5,
  TRADE_CANCEL_INTERNAL = 6,
  TradeCancelReason_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  TradeCancelReason_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool TradeCancelReason_IsValid(int value);
constexpr TradeCancelReason TradeCancelReason_MIN = TRADE_CANCEL_NONE;
constexpr TradeCancelReason TradeCancelReason_MAX = TRADE_CANCEL_INTERNAL;
constexpr int TradeCancelReason_ARRAYSIZE = TradeCancelReason_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* TradeCancelReason_descriptor();
template<typename T>
inline const std::string& TradeCancelReason_Name(T enum_t_value) {
  static_assert(::std::is_same<T, TradeCancelReason>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function TradeCancelReason_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    TradeCancelReason_descriptor(), enum_t_value);
}
inline bool TradeCancelReason_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, TradeCancelReason* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<TradeCancelReason>(
    TradeCancelReason_descriptor(), name, value);
}
enum TradeFailCode : int {
  TRADE_FAIL_NONE = 0,
  TRADE_FAIL_INVALID_TARGET = 1,
  TRADE_FAIL_ALREADY_TRADING = 2,
  TRADE_FAIL_DISTANCE_TOO_FAR = 3,
  TRADE_FAIL_INVALID_STATE = 4,
  TRADE_FAIL_INVALID_ITEM = 5,
  TRADE_FAIL_INVENTORY_FULL = 6,
  TRADE_FAIL_INTERNAL = 7,
  TRADE_FAIL_REJECTED = 8,
  TradeFailCode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  TradeFailCode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool TradeFailCode_IsValid(int value);
constexpr TradeFailCode TradeFailCode_MIN = TRADE_FAIL_NONE;
constexpr TradeFailCode TradeFailCode_MAX = TRADE_FAIL_REJECTED;
constexpr int TradeFailCode_ARRAYSIZE = TradeFailCode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* TradeFailCode_descriptor();
template<typename T>
inline const std::string& TradeFailCode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, TradeFailCode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function TradeFailCode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    TradeFailCode_descriptor(), enum_t_value);
}
inline bool TradeFailCode_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, TradeFailCode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<TradeFailCode>(
    TradeFailCode_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Protocol::MoveState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::MoveState>() {
  return ::Protocol::MoveState_descriptor();
}
template <> struct is_proto_enum< ::Protocol::ActionState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::ActionState>() {
  return ::Protocol::ActionState_descriptor();
}
template <> struct is_proto_enum< ::Protocol::PlayerType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::PlayerType>() {
  return ::Protocol::PlayerType_descriptor();
}
template <> struct is_proto_enum< ::Protocol::ObjectType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::ObjectType>() {
  return ::Protocol::ObjectType_descriptor();
}
template <> struct is_proto_enum< ::Protocol::ItemType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::ItemType>() {
  return ::Protocol::ItemType_descriptor();
}
template <> struct is_proto_enum< ::Protocol::SkillType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::SkillType>() {
  return ::Protocol::SkillType_descriptor();
}
template <> struct is_proto_enum< ::Protocol::ConnectStatus> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::ConnectStatus>() {
  return ::Protocol::ConnectStatus_descriptor();
}
template <> struct is_proto_enum< ::Protocol::RoomType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::RoomType>() {
  return ::Protocol::RoomType_descriptor();
}
template <> struct is_proto_enum< ::Protocol::PresenceStatus> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::PresenceStatus>() {
  return ::Protocol::PresenceStatus_descriptor();
}
template <> struct is_proto_enum< ::Protocol::FriendStatus> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::FriendStatus>() {
  return ::Protocol::FriendStatus_descriptor();
}
template <> struct is_proto_enum< ::Protocol::PartyOp> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::PartyOp>() {
  return ::Protocol::PartyOp_descriptor();
}
template <> struct is_proto_enum< ::Protocol::PartyResultReason> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::PartyResultReason>() {
  return ::Protocol::PartyResultReason_descriptor();
}
template <> struct is_proto_enum< ::Protocol::QuickSlotRefType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::QuickSlotRefType>() {
  return ::Protocol::QuickSlotRefType_descriptor();
}
template <> struct is_proto_enum< ::Protocol::TradeCancelReason> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::TradeCancelReason>() {
  return ::Protocol::TradeCancelReason_descriptor();
}
template <> struct is_proto_enum< ::Protocol::TradeFailCode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::TradeFailCode>() {
  return ::Protocol::TradeFailCode_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto
