// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghQcm90b2NvbCo3CglNb3ZlU3RhdGUSDQoJTU9WRV9J",
            "RExFEAASDAoITU9WRV9SVU4QARINCglNT1ZFX0pVTVAQAipkCgtBY3Rpb25T",
            "dGF0ZRIPCgtBQ1RJT05fSURMRRAAEhEKDUFDVElPTl9BVFRBQ0sQARIPCgtB",
            "Q1RJT05fREVBRBACEhAKDEFDVElPTl9TS0lMTBADEg4KCkFDVElPTl9ISVQQ",
            "BCpUCgpQbGF5ZXJUeXBlEg8KC1BMQVlFUl9OT05FEAASEQoNUExBWUVSX0tO",
            "SUdIVBABEg8KC1BMQVlFUl9NQUdFEAISEQoNUExBWUVSX0FSQ0hFUhADKm8K",
            "Ck9iamVjdFR5cGUSFAoQT0JKRUNUX1RZUEVfTk9ORRAAEhYKEk9CSkVDVF9U",
            "WVBFX1BMQVlFUhABEhcKE09CSkVDVF9UWVBFX01PTlNURVIQAhIaChZPQkpF",
            "Q1RfVFlQRV9QUk9KRUNUSUxFEAMqYwoISXRlbVR5cGUSEgoOSVRFTV9UWVBF",
            "X05PTkUQABIUChBJVEVNX1RZUEVfV0VBUE9OEAESEwoPSVRFTV9UWVBFX0FS",
            "TU9SEAISGAoUSVRFTV9UWVBFX0NPTlNVTUFCTEUQAyptCglTa2lsbFR5cGUS",
            "DgoKU0tJTExfTk9ORRAAEg4KClNLSUxMX0FVVE8QARIUChBTS0lMTF9QUk9K",
            "RUNUSUxFEAISFQoRU0tJTExfQVJFQV9DSVJDTEUQAxITCg9TS0lMTF9BUkVB",
            "X0NPTkUQBCpICg1Db25uZWN0U3RhdHVzEg4KCkNPTk5FQ1RfT0sQABIQCgxD",
            "T05ORUNUX0ZBSUwQARIVChFDT05ORUNUX1JFQ09OTkVDVBACKjwKCFJvb21U",
            "eXBlEhAKDFJPT01fUFJJVkFURRAAEg4KClJPT01fR1JPVVAQARIOCgpST09N",
            "X0dVSUxEEAIqQAoOUHJlc2VuY2VTdGF0dXMSCwoHT0ZGTElORRAAEgoKBk9O",
            "TElORRABEgsKB0lOX0dBTUUQAhIICgRBV0FZEAMqNgoMRnJpZW5kU3RhdHVz",
            "EgsKB1BFTkRJTkcQABIMCghBQ0NFUFRFRBABEgsKB0JMT0NLRUQQAirUAQoH",
            "UGFydHlPcBIRCg1QQVJUWV9PUF9OT05FEAASEwoPUEFSVFlfT1BfQ1JFQVRF",
            "EGQSEwoPUEFSVFlfT1BfSU5WSVRFEGUSGgoWUEFSVFlfT1BfSU5WSVRFX0FD",
            "Q0VQVBBmEhoKFlBBUlRZX09QX0lOVklURV9SRUpFQ1QQZxISCg5QQVJUWV9P",
            "UF9MRUFWRRBuEhEKDVBBUlRZX09QX0tJQ0sQbxIUChBQQVJUWV9PUF9ESVNC",
            "QU5EEHASFwoTUEFSVFlfT1BfU1RBVFVTX1JFURB4KvMCChFQYXJ0eVJlc3Vs",
            "dFJlYXNvbhIVChFQQVJUWV9SRUFTT05fTk9ORRAAEhQKD1BBUlRZX1JFQVNP",
            "Tl9PSxDoBxIbChZQQVJUWV9SRUFTT05fTk9fVEFSR0VUEOkHEiIKHVBBUlRZ",
            "X1JFQVNPTl9BTFJFQURZX0lOX1BBUlRZEOoHEh4KGVBBUlRZX1JFQVNPTl9O",
            "T1RfSU5fUEFSVFkQ6wcSHAoXUEFSVFlfUkVBU09OX05PVF9MRUFERVIQ7AcS",
            "HAoXUEFSVFlfUkVBU09OX05PVF9NRU1CRVIQ7QcSHwoaUEFSVFlfUkVBU09O",
            "X0lOVkFMSURfUEFSVFkQ7gcSHQoYUEFSVFlfUkVBU09OX1NFTEZfVEFSR0VU",
            "EO8HEhYKEVBBUlRZX1JFQVNPTl9GVUxMEPAHEhoKFVBBUlRZX1JFQVNPTl9S",
            "RUpFQ1RFRBDxBxIgChtQQVJUWV9SRUFTT05fSU5URVJOQUxfRVJST1IQywgq",
            "OgoQUXVpY2tTbG90UmVmVHlwZRILCgdRU19OT05FEAASCwoHUVNfSVRFTRAB",
            "EgwKCFFTX1NLSUxMEAIqzgEKEVRyYWRlQ2FuY2VsUmVhc29uEhUKEVRSQURF",
            "X0NBTkNFTF9OT05FEAASGAoUVFJBREVfQ0FOQ0VMX0JZX1NFTEYQARIZChVU",
            "UkFERV9DQU5DRUxfREVDTElORUQQAhIbChdUUkFERV9DQU5DRUxfRElTQ09O",
            "TkVDVBADEhsKF1RSQURFX0NBTkNFTF9NQVBfQ0hBTkdFEAQSGAoUVFJBREVf",
            "Q0FOQ0VMX1RJTUVPVVQQBRIZChVUUkFERV9DQU5DRUxfSU5URVJOQUwQBiqw",
            "AgoNVHJhZGVGYWlsQ29kZRITCg9UUkFERV9GQUlMX05PTkUQABIdChlUUkFE",
            "RV9GQUlMX0lOVkFMSURfVEFSR0VUEAESHgoaVFJBREVfRkFJTF9BTFJFQURZ",
            "X1RSQURJTkcQAhIfChtUUkFERV9GQUlMX0RJU1RBTkNFX1RPT19GQVIQAxIc",
            "ChhUUkFERV9GQUlMX0lOVkFMSURfU1RBVEUQBBIbChdUUkFERV9GQUlMX0lO",
            "VkFMSURfSVRFTRAFEh0KGVRSQURFX0ZBSUxfSU5WRU5UT1JZX0ZVTEwQBhIX",
            "ChNUUkFERV9GQUlMX0lOVEVSTkFMEAcSFwoTVFJBREVfRkFJTF9SRUpFQ1RF",
            "RBAIEh4KGlRSQURFX0ZBSUxfTk9UX0VOT1VHSF9HT0xEEAliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protocol.MoveState), typeof(global::Protocol.ActionState), typeof(global::Protocol.PlayerType), typeof(global::Protocol.ObjectType), typeof(global::Protocol.ItemType), typeof(global::Protocol.SkillType), typeof(global::Protocol.ConnectStatus), typeof(global::Protocol.RoomType), typeof(global::Protocol.PresenceStatus), typeof(global::Protocol.FriendStatus), typeof(global::Protocol.PartyOp), typeof(global::Protocol.PartyResultReason), typeof(global::Protocol.QuickSlotRefType), typeof(global::Protocol.TradeCancelReason), typeof(global::Protocol.TradeFailCode), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// ===== [Game Logic] 플레이어 행동 상태 =====
  /// </summary>
  public enum MoveState {
    /// <summary>
    /// 정지
    /// </summary>
    [pbr::OriginalName("MOVE_IDLE")] MoveIdle = 0,
    /// <summary>
    /// 달리기
    /// </summary>
    [pbr::OriginalName("MOVE_RUN")] MoveRun = 1,
    /// <summary>
    /// 점프
    /// </summary>
    [pbr::OriginalName("MOVE_JUMP")] MoveJump = 2,
  }

  /// <summary>
  /// [New] 행동 상태 정의
  /// </summary>
  public enum ActionState {
    /// <summary>
    /// 아무것도 안 함 (평온)
    /// </summary>
    [pbr::OriginalName("ACTION_IDLE")] ActionIdle = 0,
    /// <summary>
    /// 기본 공격
    /// </summary>
    [pbr::OriginalName("ACTION_ATTACK")] ActionAttack = 1,
    /// <summary>
    /// 사망
    /// </summary>
    [pbr::OriginalName("ACTION_DEAD")] ActionDead = 2,
    /// <summary>
    /// 스킬 사용
    /// </summary>
    [pbr::OriginalName("ACTION_SKILL")] ActionSkill = 3,
    /// <summary>
    /// 피격 (경직)
    /// </summary>
    [pbr::OriginalName("ACTION_HIT")] ActionHit = 4,
  }

  /// <summary>
  /// ===== [Game Logic] 플레이어 직업 타입 =====
  /// </summary>
  public enum PlayerType {
    [pbr::OriginalName("PLAYER_NONE")] PlayerNone = 0,
    [pbr::OriginalName("PLAYER_KNIGHT")] PlayerKnight = 1,
    [pbr::OriginalName("PLAYER_MAGE")] PlayerMage = 2,
    [pbr::OriginalName("PLAYER_ARCHER")] PlayerArcher = 3,
  }

  public enum ObjectType {
    [pbr::OriginalName("OBJECT_TYPE_NONE")] None = 0,
    [pbr::OriginalName("OBJECT_TYPE_PLAYER")] Player = 1,
    [pbr::OriginalName("OBJECT_TYPE_MONSTER")] Monster = 2,
    [pbr::OriginalName("OBJECT_TYPE_PROJECTILE")] Projectile = 3,
  }

  /// <summary>
  /// ===== [Item] 아이템 타입 (NEW) =====
  /// </summary>
  public enum ItemType {
    [pbr::OriginalName("ITEM_TYPE_NONE")] None = 0,
    /// <summary>
    /// 무기
    /// </summary>
    [pbr::OriginalName("ITEM_TYPE_WEAPON")] Weapon = 1,
    /// <summary>
    /// 방어구
    /// </summary>
    [pbr::OriginalName("ITEM_TYPE_ARMOR")] Armor = 2,
    /// <summary>
    /// 소비 아이템 (포션 등)
    /// </summary>
    [pbr::OriginalName("ITEM_TYPE_CONSUMABLE")] Consumable = 3,
  }

  /// <summary>
  ///======[Skill] 스킬관련=========
  /// </summary>
  public enum SkillType {
    [pbr::OriginalName("SKILL_NONE")] SkillNone = 0,
    /// <summary>
    /// 평타 (단일 타겟)
    /// </summary>
    [pbr::OriginalName("SKILL_AUTO")] SkillAuto = 1,
    /// <summary>
    /// 투사체 (화살, 파이어볼)
    /// </summary>
    [pbr::OriginalName("SKILL_PROJECTILE")] SkillProjectile = 2,
    /// <summary>
    /// 원형 범위 (자폭, 주변 광역기)
    /// </summary>
    [pbr::OriginalName("SKILL_AREA_CIRCLE")] SkillAreaCircle = 3,
    /// <summary>
    /// 부채꼴 (전방 브레스)
    /// </summary>
    [pbr::OriginalName("SKILL_AREA_CONE")] SkillAreaCone = 4,
  }

  /// <summary>
  /// ===== [Network] 연결 상태 =====
  /// </summary>
  public enum ConnectStatus {
    [pbr::OriginalName("CONNECT_OK")] ConnectOk = 0,
    [pbr::OriginalName("CONNECT_FAIL")] ConnectFail = 1,
    [pbr::OriginalName("CONNECT_RECONNECT")] ConnectReconnect = 2,
  }

  /// <summary>
  /// ===== [Chat] 채팅 룸 타입 =====
  /// </summary>
  public enum RoomType {
    /// <summary>
    /// 1:1
    /// </summary>
    [pbr::OriginalName("ROOM_PRIVATE")] RoomPrivate = 0,
    /// <summary>
    /// 단체방
    /// </summary>
    [pbr::OriginalName("ROOM_GROUP")] RoomGroup = 1,
    /// <summary>
    /// 길드/운영 확장
    /// </summary>
    [pbr::OriginalName("ROOM_GUILD")] RoomGuild = 2,
  }

  /// <summary>
  /// ===== [Social] Presence 상태 =====
  /// </summary>
  public enum PresenceStatus {
    [pbr::OriginalName("OFFLINE")] Offline = 0,
    [pbr::OriginalName("ONLINE")] Online = 1,
    [pbr::OriginalName("IN_GAME")] InGame = 2,
    [pbr::OriginalName("AWAY")] Away = 3,
  }

  /// <summary>
  /// ===== [Social] 친구 요청 상태 =====
  /// </summary>
  public enum FriendStatus {
    [pbr::OriginalName("PENDING")] Pending = 0,
    [pbr::OriginalName("ACCEPTED")] Accepted = 1,
    [pbr::OriginalName("BLOCKED")] Blocked = 2,
  }

  /// <summary>
  /// ===== [Party] 파티 요청 종류 =====
  /// </summary>
  public enum PartyOp {
    [pbr::OriginalName("PARTY_OP_NONE")] None = 0,
    [pbr::OriginalName("PARTY_OP_CREATE")] Create = 100,
    [pbr::OriginalName("PARTY_OP_INVITE")] Invite = 101,
    [pbr::OriginalName("PARTY_OP_INVITE_ACCEPT")] InviteAccept = 102,
    [pbr::OriginalName("PARTY_OP_INVITE_REJECT")] InviteReject = 103,
    [pbr::OriginalName("PARTY_OP_LEAVE")] Leave = 110,
    [pbr::OriginalName("PARTY_OP_KICK")] Kick = 111,
    [pbr::OriginalName("PARTY_OP_DISBAND")] Disband = 112,
    /// <summary>
    /// (선택) 디버그/로깅용
    /// </summary>
    [pbr::OriginalName("PARTY_OP_STATUS_REQ")] StatusReq = 120,
  }

  /// <summary>
  /// ===== [Party] 실패/거절 사유 =====
  /// </summary>
  public enum PartyResultReason {
    [pbr::OriginalName("PARTY_REASON_NONE")] PartyReasonNone = 0,
    [pbr::OriginalName("PARTY_REASON_OK")] PartyReasonOk = 1000,
    /// <summary>
    /// 대상 없음(오프라인/세션 없음)
    /// </summary>
    [pbr::OriginalName("PARTY_REASON_NO_TARGET")] PartyReasonNoTarget = 1001,
    /// <summary>
    /// 대상 또는 내가 이미 파티 있음
    /// </summary>
    [pbr::OriginalName("PARTY_REASON_ALREADY_IN_PARTY")] PartyReasonAlreadyInParty = 1002,
    /// <summary>
    /// 파티가 없는데 요청함
    /// </summary>
    [pbr::OriginalName("PARTY_REASON_NOT_IN_PARTY")] PartyReasonNotInParty = 1003,
    /// <summary>
    /// 리더만 가능한 동작
    /// </summary>
    [pbr::OriginalName("PARTY_REASON_NOT_LEADER")] PartyReasonNotLeader = 1004,
    /// <summary>
    /// 파티원이 아님
    /// </summary>
    [pbr::OriginalName("PARTY_REASON_NOT_MEMBER")] PartyReasonNotMember = 1005,
    /// <summary>
    /// partyId가 잘못됨
    /// </summary>
    [pbr::OriginalName("PARTY_REASON_INVALID_PARTY")] PartyReasonInvalidParty = 1006,
    /// <summary>
    /// 자기 자신 초대/추방 등
    /// </summary>
    [pbr::OriginalName("PARTY_REASON_SELF_TARGET")] PartyReasonSelfTarget = 1007,
    /// <summary>
    /// 파티 정원 초과(나중에)
    /// </summary>
    [pbr::OriginalName("PARTY_REASON_FULL")] PartyReasonFull = 1008,
    /// <summary>
    /// 초대 거절
    /// </summary>
    [pbr::OriginalName("PARTY_REASON_REJECTED")] PartyReasonRejected = 1009,
    /// <summary>
    /// 서버 내부 에러
    /// </summary>
    [pbr::OriginalName("PARTY_REASON_INTERNAL_ERROR")] PartyReasonInternalError = 1099,
  }

  public enum QuickSlotRefType {
    [pbr::OriginalName("QS_NONE")] QsNone = 0,
    [pbr::OriginalName("QS_ITEM")] QsItem = 1,
    [pbr::OriginalName("QS_SKILL")] QsSkill = 2,
  }

  /// <summary>
  /// ===== [Trade] =====
  /// </summary>
  public enum TradeCancelReason {
    [pbr::OriginalName("TRADE_CANCEL_NONE")] TradeCancelNone = 0,
    [pbr::OriginalName("TRADE_CANCEL_BY_SELF")] TradeCancelBySelf = 1,
    [pbr::OriginalName("TRADE_CANCEL_DECLINED")] TradeCancelDeclined = 2,
    [pbr::OriginalName("TRADE_CANCEL_DISCONNECT")] TradeCancelDisconnect = 3,
    [pbr::OriginalName("TRADE_CANCEL_MAP_CHANGE")] TradeCancelMapChange = 4,
    [pbr::OriginalName("TRADE_CANCEL_TIMEOUT")] TradeCancelTimeout = 5,
    [pbr::OriginalName("TRADE_CANCEL_INTERNAL")] TradeCancelInternal = 6,
  }

  public enum TradeFailCode {
    [pbr::OriginalName("TRADE_FAIL_NONE")] TradeFailNone = 0,
    [pbr::OriginalName("TRADE_FAIL_INVALID_TARGET")] TradeFailInvalidTarget = 1,
    [pbr::OriginalName("TRADE_FAIL_ALREADY_TRADING")] TradeFailAlreadyTrading = 2,
    [pbr::OriginalName("TRADE_FAIL_DISTANCE_TOO_FAR")] TradeFailDistanceTooFar = 3,
    [pbr::OriginalName("TRADE_FAIL_INVALID_STATE")] TradeFailInvalidState = 4,
    [pbr::OriginalName("TRADE_FAIL_INVALID_ITEM")] TradeFailInvalidItem = 5,
    [pbr::OriginalName("TRADE_FAIL_INVENTORY_FULL")] TradeFailInventoryFull = 6,
    [pbr::OriginalName("TRADE_FAIL_INTERNAL")] TradeFailInternal = 7,
    [pbr::OriginalName("TRADE_FAIL_REJECTED")] TradeFailRejected = 8,
    [pbr::OriginalName("TRADE_FAIL_NOT_ENOUGH_GOLD")] TradeFailNotEnoughGold = 9,
  }

  #endregion

}

#endregion Designer generated code
