// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghQcm90b2NvbCo3CglNb3ZlU3RhdGUSDQoJTU9WRV9J",
            "RExFEAASDAoITU9WRV9SVU4QARINCglNT1ZFX0pVTVAQAipkCgtBY3Rpb25T",
            "dGF0ZRIPCgtBQ1RJT05fSURMRRAAEhEKDUFDVElPTl9BVFRBQ0sQARIPCgtB",
            "Q1RJT05fREVBRBACEhAKDEFDVElPTl9TS0lMTBADEg4KCkFDVElPTl9ISVQQ",
            "BCpUCgpQbGF5ZXJUeXBlEg8KC1BMQVlFUl9OT05FEAASEQoNUExBWUVSX0tO",
            "SUdIVBABEg8KC1BMQVlFUl9NQUdFEAISEQoNUExBWUVSX0FSQ0hFUhADKm8K",
            "Ck9iamVjdFR5cGUSFAoQT0JKRUNUX1RZUEVfTk9ORRAAEhYKEk9CSkVDVF9U",
            "WVBFX1BMQVlFUhABEhcKE09CSkVDVF9UWVBFX01PTlNURVIQAhIaChZPQkpF",
            "Q1RfVFlQRV9QUk9KRUNUSUxFEAMqYwoISXRlbVR5cGUSEgoOSVRFTV9UWVBF",
            "X05PTkUQABIUChBJVEVNX1RZUEVfV0VBUE9OEAESEwoPSVRFTV9UWVBFX0FS",
            "TU9SEAISGAoUSVRFTV9UWVBFX0NPTlNVTUFCTEUQAypICg1Db25uZWN0U3Rh",
            "dHVzEg4KCkNPTk5FQ1RfT0sQABIQCgxDT05ORUNUX0ZBSUwQARIVChFDT05O",
            "RUNUX1JFQ09OTkVDVBACKjwKCFJvb21UeXBlEhAKDFJPT01fUFJJVkFURRAA",
            "Eg4KClJPT01fR1JPVVAQARIOCgpST09NX0dVSUxEEAIqQAoOUHJlc2VuY2VT",
            "dGF0dXMSCwoHT0ZGTElORRAAEgoKBk9OTElORRABEgsKB0lOX0dBTUUQAhII",
            "CgRBV0FZEAMqNgoMRnJpZW5kU3RhdHVzEgsKB1BFTkRJTkcQABIMCghBQ0NF",
            "UFRFRBABEgsKB0JMT0NLRUQQAmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protocol.MoveState), typeof(global::Protocol.ActionState), typeof(global::Protocol.PlayerType), typeof(global::Protocol.ObjectType), typeof(global::Protocol.ItemType), typeof(global::Protocol.ConnectStatus), typeof(global::Protocol.RoomType), typeof(global::Protocol.PresenceStatus), typeof(global::Protocol.FriendStatus), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// ===== [Game Logic] 플레이어 행동 상태 =====
  /// </summary>
  public enum MoveState {
    /// <summary>
    /// 정지
    /// </summary>
    [pbr::OriginalName("MOVE_IDLE")] MoveIdle = 0,
    /// <summary>
    /// 달리기
    /// </summary>
    [pbr::OriginalName("MOVE_RUN")] MoveRun = 1,
    /// <summary>
    /// 점프
    /// </summary>
    [pbr::OriginalName("MOVE_JUMP")] MoveJump = 2,
  }

  /// <summary>
  /// [New] 행동 상태 정의
  /// </summary>
  public enum ActionState {
    /// <summary>
    /// 아무것도 안 함 (평온)
    /// </summary>
    [pbr::OriginalName("ACTION_IDLE")] ActionIdle = 0,
    /// <summary>
    /// 기본 공격
    /// </summary>
    [pbr::OriginalName("ACTION_ATTACK")] ActionAttack = 1,
    /// <summary>
    /// 사망
    /// </summary>
    [pbr::OriginalName("ACTION_DEAD")] ActionDead = 2,
    /// <summary>
    /// 스킬 사용
    /// </summary>
    [pbr::OriginalName("ACTION_SKILL")] ActionSkill = 3,
    /// <summary>
    /// 피격 (경직)
    /// </summary>
    [pbr::OriginalName("ACTION_HIT")] ActionHit = 4,
  }

  /// <summary>
  /// ===== [Game Logic] 플레이어 직업 타입 =====
  /// </summary>
  public enum PlayerType {
    [pbr::OriginalName("PLAYER_NONE")] PlayerNone = 0,
    [pbr::OriginalName("PLAYER_KNIGHT")] PlayerKnight = 1,
    [pbr::OriginalName("PLAYER_MAGE")] PlayerMage = 2,
    [pbr::OriginalName("PLAYER_ARCHER")] PlayerArcher = 3,
  }

  public enum ObjectType {
    [pbr::OriginalName("OBJECT_TYPE_NONE")] None = 0,
    [pbr::OriginalName("OBJECT_TYPE_PLAYER")] Player = 1,
    [pbr::OriginalName("OBJECT_TYPE_MONSTER")] Monster = 2,
    [pbr::OriginalName("OBJECT_TYPE_PROJECTILE")] Projectile = 3,
  }

  /// <summary>
  /// ===== [Item] 아이템 타입 (NEW) =====
  /// </summary>
  public enum ItemType {
    [pbr::OriginalName("ITEM_TYPE_NONE")] None = 0,
    /// <summary>
    /// 무기
    /// </summary>
    [pbr::OriginalName("ITEM_TYPE_WEAPON")] Weapon = 1,
    /// <summary>
    /// 방어구
    /// </summary>
    [pbr::OriginalName("ITEM_TYPE_ARMOR")] Armor = 2,
    /// <summary>
    /// 소비 아이템 (포션 등)
    /// </summary>
    [pbr::OriginalName("ITEM_TYPE_CONSUMABLE")] Consumable = 3,
  }

  /// <summary>
  /// ===== [Network] 연결 상태 =====
  /// </summary>
  public enum ConnectStatus {
    [pbr::OriginalName("CONNECT_OK")] ConnectOk = 0,
    [pbr::OriginalName("CONNECT_FAIL")] ConnectFail = 1,
    [pbr::OriginalName("CONNECT_RECONNECT")] ConnectReconnect = 2,
  }

  /// <summary>
  /// ===== [Chat] 채팅 룸 타입 =====
  /// </summary>
  public enum RoomType {
    /// <summary>
    /// 1:1
    /// </summary>
    [pbr::OriginalName("ROOM_PRIVATE")] RoomPrivate = 0,
    /// <summary>
    /// 단체방
    /// </summary>
    [pbr::OriginalName("ROOM_GROUP")] RoomGroup = 1,
    /// <summary>
    /// 길드/운영 확장
    /// </summary>
    [pbr::OriginalName("ROOM_GUILD")] RoomGuild = 2,
  }

  /// <summary>
  /// ===== [Social] Presence 상태 =====
  /// </summary>
  public enum PresenceStatus {
    [pbr::OriginalName("OFFLINE")] Offline = 0,
    [pbr::OriginalName("ONLINE")] Online = 1,
    [pbr::OriginalName("IN_GAME")] InGame = 2,
    [pbr::OriginalName("AWAY")] Away = 3,
  }

  /// <summary>
  /// ===== [Social] 친구 요청 상태 =====
  /// </summary>
  public enum FriendStatus {
    [pbr::OriginalName("PENDING")] Pending = 0,
    [pbr::OriginalName("ACCEPTED")] Accepted = 1,
    [pbr::OriginalName("BLOCKED")] Blocked = 2,
  }

  #endregion

}

#endregion Designer generated code
